### ISSUE TITLE
Unfortunelly doesn't work as it should...

### ISSUE THREAD

**Issue by heavyrain266** [sticky-tea/afetch#1]
Hi, I'm having all deps installed (nixos) and almost every thing is "undefined" + art is broken... result image below

![image](https://user-images.githubusercontent.com/71175207/107094897-be2eed80-67ff-11eb-9f0b-a573fb499653.png)

**Comment by sticky-tea** [comment]
> Hi, I'm having all deps installed (nixos) and almost every thing is "undefined" + art is broken... result image below
> 
> ![image](https://user-images.githubusercontent.com/71175207/107094897-be2eed80-67ff-11eb-9f0b-a573fb499653.png)

Can you please show output of "whereis whoami" and "whereis uname"? I will add pathes tomorrow

**Comment by heavyrain266** [comment]
NixOS has non-standard FHS and doesn't even provide paths like `/usr/bin` uses `/nix/store` instead

`[nix-shell:~]$ whereis whoami
whoami: /nix/store/0y7rv26ffa359wvqd3js94cn73z882fg-coreutils-8.32/bin/whoami /nix/store/jf5p1d3hh1ypzk20xr1x595gdkkipiq7-system-path/bin/whoami`

`[nix-shell:~]$ whereis uname
uname: /nix/store/0y7rv26ffa359wvqd3js94cn73z882fg-coreutils-8.32/bin/uname /nix/store/jf5p1d3hh1ypzk20xr1x595gdkkipiq7-system-path/bin/unam`

**Comment by sticky-tea** [comment]
> NixOS has non-standard FHS and doesn't even provide paths like `/usr/bin` uses `/nix/store` instead
> 
> `[nix-shell:~]$ whereis whoami whoami: /nix/store/0y7rv26ffa359wvqd3js94cn73z882fg-coreutils-8.32/bin/whoami /nix/store/jf5p1d3hh1ypzk20xr1x595gdkkipiq7-system-path/bin/whoami`
> 
> `[nix-shell:~]$ whereis uname uname: /nix/store/0y7rv26ffa359wvqd3js94cn73z882fg-coreutils-8.32/bin/uname /nix/store/jf5p1d3hh1ypzk20xr1x595gdkkipiq7-system-path/bin/unam`

Please check it now. I replaced almost all shell calls with syscalls, but other bugs can appear

**Comment by heavyrain266** [comment]
Here result after `git pull`
![image](https://user-images.githubusercontent.com/71175207/107146989-66010400-6943-11eb-8e50-1f4ca3bd6871.png)

**Comment by sticky-tea** [comment]
> Here result after `git pull`
> ![image](https://user-images.githubusercontent.com/71175207/107146989-66010400-6943-11eb-8e50-1f4ca3bd6871.png)

Nice! I'll think what to do with OS, thank you for testing.
Btw cool rice :)

**Comment by heavyrain266** [comment]
Thank, I think it's time to close issue.
